name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'akilli_kart_web/package-lock.json'

      - name: Install Dependencies
        working-directory: akilli_kart_web
        run: npm ci

      - name: Build Application
        working-directory: akilli_kart_web
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'refs/heads/main'
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMART_CARD_HYBRID }}'
          channelId: live
          projectId: smart-card-hybrid
          entryPoint: akilli_kart_web
